plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.vchristina02.papyrusreader'
    //noinspection GradleDependency
    compileSdk = 35

    defaultConfig {
        applicationId "com.vchristina02.papyrusreader"
        minSdk 24
        //noinspection OldTargetApi
        targetSdk 35
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {

    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
    implementation(libs.itextg)
    implementation(libs.webkit)
    implementation(libs.gson)
    implementation(libs.glide)

    implementation (libs.room.runtime)
    annotationProcessor (libs.androidx.room.compiler)
    testImplementation (libs.androidx.room.testing)

}